import { StyleSheet, Platform } from 'react-native';
import { COLORS } from './globalStyles';

export default StyleSheet.create({
  wrapper: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 50 : 30,
    left: 15,
    right: 15,
    flexDirection: 'row',
    alignItems: 'flex-start',
    zIndex: 10,
  },
  painelExpandido: {
    flex: 1,
    backgroundColor: COLORS.bgWhite,
    borderRadius: 16,
    padding: 12,
    marginHorizontal: 8,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 5,
  },
  painelColapsado: {
    width: 44,
    height: 44,
    backgroundColor: COLORS.bgWhite,
    borderRadius: 22,
    marginHorizontal: 8,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 10,
    marginBottom: 6,
    backgroundColor: COLORS.bgInput,
  },
  inputEndereco: {
    flex: 1,
    height: 38,
    fontSize: 14,
    color: COLORS.textDark,
  },
  iconeLimpar: {
    color: COLORS.textLight,
    fontSize: 14,
    padding: 4,
  },
  botaoInverter: {
    alignSelf: 'center',
    marginBottom: 6,
  },
  iconeInverter: {
    fontSize: 20,
    color: COLORS.primary,
    textAlign: 'center',
  },
  buscarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  labelPrioridade: {
    fontSize: 12,
    color: COLORS.textMid,
    marginRight: 6,
  },
  selectToque: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    padding: 7,
    backgroundColor: COLORS.bgInput,
  },
  selectTexto: {
    fontSize: 13,
    color: COLORS.textDark,
  },
  botaoChevron: {
    alignSelf: 'center',
    marginTop: 6,
    padding: 4,
  },
  iconeChevron: {
    fontSize: 16,
    color: COLORS.textMid,
    textAlign: 'center',
  },
  // Adicione ao final do StyleSheet.create({...})
chevronFixo: {
  position: 'absolute',
  right: 0,
  top: 0,
  width: 44,
  height: 44,
  backgroundColor: 'rgba(255,255,255,0.97)',
  borderRadius: 22,
  justifyContent: 'center',
  alignItems: 'center',
  shadowColor: '#000',
  shadowOpacity: 0.1,
  shadowRadius: 4,
  elevation: 3,
},
});